### ISSUE TITLE
DAY ONE calendar 페이지 레이아웃 작성

### ISSUE THREAD

**Issue by hjhjhj00** [junhee0110/DAYONE_Web#4]
# 작업 개요

달력과 동방 예약 정보가 있는 페이지를 제작한다.

# 체크 리스트

확인 해야 할 것, 해야 할 것 리스트를 작성해주세요.
- [x] Header
- [x] 달력 부분
- [x] 간략 정보 부분

**Comment by hjhjhj00** [comment]
**달력 크기**
모바일 : 75%
화면크기 576px ~ 992px: 50%
화면크기 992px 이상: 41%

**Comment by hjhjhj00** [comment]
**Header**
높이: 5%
오른쪽, 왼쪽에 각각 뒤로가기, 메뉴 버튼 생성

**Comment by hjhjhj00** [comment]
**Information**
높이: 40%
가운데에 예약하기 버튼 생성.

**Comment by junhee0110** [comment]
@hjhjhj00 레이아웃 작성은 다 된걸로 아는데, Pull Request 작성해주세요!

**Comment by hjhjhj00** [comment]
확인 부탁드립니다!
