### ISSUE TITLE
DAYONE 디자인 진행상황

### ISSUE THREAD

**Issue by Heojihyang** [junhee0110/DAYONE_Web#5]
# 작업 개요
피드백 수정 완료 후 
달력, 예약 페이지 제작, 세부디자인 시작

# 체크 리스트

확인 해야 할 것, 해야 할 것 리스트를 작성해주세요.
- [x] 달력 디자인
- [x] 예약창 만들기
- [x] information 화면 구성 초안제작

**Comment by Heojihyang** [comment]
Dayone 로고 Ai 제작 후 image 대체

**Comment by Heojihyang** [comment]
달력 디자인 완료

**Comment by Heojihyang** [comment]
Home 레이어 2번째 블록 예시 사진 삽입 
..어떤가요..?

**Comment by junhee0110** [comment]
방금 확인했습니다! 사진 삽입된 게 확실히 느낌있고 좋긴 한데, 텍스트의 위치나 글꼴, 크기 등을 조정해야 할 것 같아요!

**Comment by Heojihyang** [comment]
피그마에 코멘트 달아주시면 수정하겠습니다 !

**Comment by hjhjhj00** [comment]
홈 화면의 캐치프라이즈 너무 예쁜데 개인적으로 Do Anything You Want가 DAYONE을 뜻한다는 게 드러나면 좋을 것 같아요,,!
DAYONE
Do
Anything
You
WANT
이런 식으로 첫번째 문자에서 대문자로 포인트로 주거나, 글자색을 다르게 하는 건 어떤가요?? 고려해보고 일단 피그마에 코멘트 달아놓을게요!

**Comment by junhee0110** [comment]
이 뒤로 이어지는 디자인에 관한 논의는 Discussion 탭에 있는 Ideas에 게시글을 만들어서 논의해주시길 바랍니다!

Issue는 논의하기에는 적절하지 않습니다

**Comment by hjhjhj00** [comment]
넵
